### ISSUE TITLE
Since the update to 1.4.0 vee-validate does no longer work

### ISSUE THREAD

**Issue by SPQRInc** [dm4t2/vue-currency-input#10]
All validation returns false.

I guess it has something to do with:

https://baianat.github.io/vee-validate/examples/custom-component.html

-> Must emit an input event whenever the value changes.

**Comment by dm4t2** [comment]
Yes, according to the vee-validate docs, it does not support custom `v-model` events. The suggested solution is to go for [validation components](https://baianat.github.io/vee-validate/guide/components.html) since this is caveat of the directive.

Regardless of this I recently figured out that the custom `v-model` event introduced in release 1.4.0 is actually unnecessary. So I'll probably rollback to the `v-model` default behavior using the `input` event.

**Comment by SPQRInc** [comment]
Great :-) I will check out the next update :-)

**Comment by dm4t2** [comment]
vee-validate should work again with release 1.4.1 🎉

**Comment by SPQRInc** [comment]
Works fine now :-) Thanks a lot!
