### ISSUE TITLE
Setting value from store does not format input

### ISSUE THREAD

**Issue by didrikg** [dm4t2/vue-currency-input#107]
Hello,

I think this is me not really understanding how this should work, I'm using Vuex to store my variables, but when they are updated elsewhere the input-field (`b-form-input`) with `v-currency` loses the formatting.

I'm using v-model and computed properties with `get()` and `set()` to update and get my values from store, I managed to reproduce the error in a sandbox here: 
https://codesandbox.io/s/vue-currency-input-set-value-programmatically-kzulx

How am I supposed to do this?

**Comment by dm4t2** [comment]
Hi, you can not use number values as model when using `v-currency` directive since it works directly on the formatted string. You need an additional state to handle both the displayed (formatted) value and its internal representation (number).

This can be encapsulated in a custom `<b-currency-input>` component:
https://codesandbox.io/s/using-vue-currency-input-with-buefy-pnl3q?file=/src/components/BCurrencyInput.vue

Hope this helps!

**Comment by alexsonnay** [comment]
Not working with last version 1.19 

https://codesandbox.io/s/using-vue-currency-input-with-buefy-7ejdo
