### ISSUE TITLE
Value range is validated after change event is emitted

### ISSUE THREAD

**Issue by matteoraf** [dm4t2/vue-currency-input#122]
If you use lazy model binding and set a valueRange for validation, the change event is fired with the non-validated value, thus the model is wrongly updated.

Sandbox: [Link](https://codesandbox.io/s/valuerange-with-lazy-model-binding-qohfu?file=/src/components/VCurrencyField.vue)

Reproduction: Insert a value out of limit (more than 100 in this case) and check console

**Comment by dm4t2** [comment]
Hi, the `native` event modifier is required when using Vuetify because the `change` event emitted by `<v-text-field>` contains the wrong value:

https://codesandbox.io/s/vue-currency-input-122-rcjd9?file=/src/components/VCurrencyField.vue

But I noticed the lazy value binding does not respect the value range for initial values, like in my Sandbox 🤔 This will be fixed.

**Comment by dm4t2** [comment]
Fixed in [Release 1.19.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.19.0) 🎉

**Comment by matteoraf** [comment]
Thank you for fixing this, but the issue is partially still there:

if you press Enter instead of clicking outside, the Change event is emitted with the wrong value.
As soon as you unblur the field, then the event is emitted again with the correct value.

Please see here: https://codesandbox.io/s/vue-currency-input-122-x7m5j?file=/src/components/VCurrencyField.vue

**Comment by dm4t2** [comment]
Same as #125.
