### ISSUE TITLE
Incorrect operation of the minimum value in the range when cleaning the field

### ISSUE THREAD

**Issue by afuno** [dm4t2/vue-currency-input#135]
I set the minimum value. It can be equal to 0.0 or 9.0 (for example). This minimum value becomes the default value.

The problem is that if I clear the field, it will remain empty.

In the example with the maximum value - if I exceed this limit, then there will be a reset to the maximum value.

It seems to me it would be logical to do the same with a minimum value. If the field is cleared, then this should be a violation of the limit rules. That is, the minimum value should be automatically set.

---

_P.S. And what about the implementation of resetting to the limits not in blur, but right away? Now that the field is in focus, I can enter a value that exceeds the limit. And it will be reset to the specified limit only when blur from the field occurs._

**Comment by dm4t2** [comment]
In this case you would not be able to clear the input anymore. I have implemented this originally already once and then reverted it later (see #49, #58). You can use the [setValue ](https://dm4t2.github.io/vue-currency-input/api/#setvalue) API method to force the desired behavior for your use case.

> P.S. And what about the implementation of resetting to the limits not in blur, but right away? Now that the field is in focus, I can enter a value that exceeds the limit. And it will be reset to the specified limit only when blur from the field occurs.

This option (`validateOnInput`) formerly existed and was removed in [Release 1.9.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.9.0). The problem was that you could not leave the value range (e.g. temporarily for corrections) and then you might be "trapped" in it.
