### ISSUE TITLE
when I load Axios, append value = 200000

### ISSUE THREAD

**Issue by khanhnam99** [dm4t2/vue-currency-input#147]
in Vuejs

default value : 100.000 ₫

when I load Axios, append value = 200000

and now  default value: 200000

I want default value:200.000 ₫, what can to I do?

**Comment by dm4t2** [comment]
Please describe your problem more clearly. I did not get it.

**Comment by Daniel4Digital** [comment]
I believe I've the same problem. 

So if I save 1000.50, it will send a float as 1000.5, the backend will save and when needed will provide me a string with "1000.50". So when I refresh the page, it will appear "1000.50" even with locale: 'pt'. When it should appear "1.000,50" since the decimal separator of pt is comma. If I rewrite on the input, it does work perfectly, but not when it loads. It doesn't parse the value with the locale. BUT if I change the locale to 'en' for example, it parses correctly 10,000.50. When 'pt' or 'pt_PT it doesn't.

Any way to bypass this?

**Comment by dm4t2** [comment]
@Daniel4Digital The initial string value must match the configured currency format. In your example the string value `"12355.50"` will result in the number value `1235550` since the decimal point is the grouping separator (and not the decimal separator). Using the string value `"12355,50"` will fix this.

I would suggest the usage of the [setValue](https://dm4t2.github.io/vue-currency-input/api/#setvalue) API method in the `mounted` lifecycle hook to set the initial value (assuming your backend provides a number/float value).

**Comment by Leinad4Mind** [comment]
I see. I'll need to create a computed then. Because the currency format depends on the user configuration. If the user change his language to English, the locale will change to en-us. In the backend I save always with decimal point. In the frontend I need to check the locale and depending the locale I'll need to make a replace on the dot for a comma.

**Comment by dm4t2** [comment]
> A method that would always receive a number with dot as decimal separator, and it would parse correctly according the locale for the first render.

@Leinad4Mind That's exactly what the `setValue` method does: https://codesandbox.io/s/vue-currency-input-set-value-programmatically-rv95r?file=/src/App.vue

**Comment by khanhnam99** [comment]
thanks
