### ISSUE TITLE
Including vue-currency-input in vue project breaks IE 11 & Edge

### ISSUE THREAD

**Issue by rfvizarra** [dm4t2/vue-currency-input#15]
Hi,

First of all, thank you for providing this library.

I just found out that a Vue project created with @vue/cli that uses vue-currency-input breaks in Internet explorer 11 and in Microsoft Edge with the following error

`"Expected identifier, string or number"`

The way to reproduce the problem is simple.

create a new project with vue with the defaults. Follow the instructions in https://dm4t2.github.io/vue-currency-input/guide/ to add Vue Currency to the project, run the project with yarn serve and open the url with IE 11 or MS Edge.

This kind of errors is usually caused by a trailing comma somewhere, but wasn't able to find one.

Best regards,
Rodrigo

**Comment by dm4t2** [comment]
Hi,
the plugin will work in Edge if you add
 ```
transpileDependencies: ['vue-currency-input']
``` 
to `vue.config.js` (see https://cli.vuejs.org/config/#transpiledependencies).

IE11 is currently not supported,

**Comment by rfvizarra** [comment]
Hi,

thanks for the information about how to fix the issue with Edge, it worked flawlessly.

May I suggest to add that information to the web page, including the information about browser support? 

So I guess it was not a bug after all.

Thanks again.

**Comment by dm4t2** [comment]
Thanks for your suggestion. I will add it in the docs.

Good news: IE11 will be supported in the next release (1.6.0) 🎉

**Comment by dm4t2** [comment]
IE11/Edge are now fully supported in release 1.6.0. 
The `transpileDependencies` config is no longer needed.

**Comment by truongx** [comment]
Most of all - thank you for your work.

Everything runs flawlessly in other browsers, but in IE11 (v11.778.18362) I have trouble making it work, so I'm reusing this issue. In dev mode I get the following errors:

`Error in created hook: "TypeError: Object doesn't support property or method 'formatToParts'"`
`Error in directive currency bind hook: "TypeError: Object doesn't support property or method 'formatToParts'"`

I thought it's caused by the lacking implementation of [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) in IE11, so I added the polyfills, but it didn't help. Perhaps i'm missing something simple here.

The [Playground](https://dm4t2.github.io/vue-currency-input/playground/) site doesn't work in IE11 either (any characters can be typed inside the input).

**Comment by dm4t2** [comment]
Hi, since [1.18.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.18.0) browser support for [Intl.NumberFormat.prototype.formatToParts()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts#Browser_compatibility) is required or needs to be [polyfilled](https://www.npmjs.com/package/intl).

Adding the following snippet to your `main.js` should work:
```
if (!Intl.NumberFormat.prototype.formatToParts) {
    Intl.NumberFormat = require('intl').NumberFormat;
    require('intl/locale-data/jsonp/<your locale>')
}
```

You can also use a version < 1.18.0 if you don't need support Arabic/Persian numbers.

**Comment by truongx** [comment]
Worked like a charm, thank you :)

**Comment by njzah** [comment]
Hi, I also have same issue in IE11. Do you have CDN for version less than 1.18.0.

**Comment by bkarlson** [comment]
Is there any way to use polyfill with dynamic locale values, i.e. based on user preferences / browser locale?

**Comment by bkarlson** [comment]
maybe a bundle w/o arabic numbers support can be a compromise for those who need slightly wider compatibility, but don't want to miss on latest vue-currency-input bugfixes..

**Comment by dm4t2** [comment]
> Hi, I also have same issue in IE11. Do you have CDN for version less than 1.18.0.

Use https://unpkg.com/vue-currency-input@1.17.3

> Is there any way to use polyfill with dynamic locale values, i.e. based on user preferences / browser locale?

What about using `navigator.language`?

> maybe a bundle w/o arabic numbers support can be a compromise for those who need slightly wider browser compatibility, but don't want to miss on latest vue-currency-input bugfixes..

No, sorry! Please use the polyfill if you need to support zombie browsers like IE11.

**Comment by bkarlson** [comment]
@dm4t2, I checked and apart from IE11, up to 3-4% of other browsers (Chrome < 64, Safari < 11 or even 12, Edge < 18 etc), do not support `formatToParts()`. Also, the polyfill itself is unmaintaned and its issues list looks scary. 

As for dynamic locale imports, my concern was not about detecting locale, but about dynamically pulling necessary jsonp upon detection... it might be that webpack 4 can do it natively for `require`,  I will explore this later.

**Comment by dm4t2** [comment]
**Good news:** In the next release (probably 1.19.0) the requirement for [Intl.NumberFormat.prototype.formatToParts()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts#Browser_compatibility) will be dropped again.

**Comment by nPaul** [comment]
> **Good news:** In the next release (probably 1.19.0) the requirement for [Intl.NumberFormat.prototype.formatToParts()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts#Browser_compatibility) will be dropped again.

Please faster :D
my users with safari 10 are indignant

**Comment by dm4t2** [comment]
[Release 1.19.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.19.0) is now available 🤤
