### ISSUE TITLE
Directive don't work with vuetify v-text-field

### ISSUE THREAD

**Issue by m4ss1m0g** [dm4t2/vue-currency-input#161]
## Description
When using `vue-currency-input` on `v-text-field` the value of v-model is the formatted value **NOT** the number.

I have replicated the issue on a [sandbox](https://codesandbox.io/s/modest-hooks-r6kc3?fontsize=14&hidenavigation=1&theme=dark)

## Steps to reproduce 1

1. Write some number to the textbox
2. exit the field
3. The binded v-model value has the formatted value

## Steps to reproduce 2

1. click the setup button
2. The value on text box IS NOT formatted

**Comment by dm4t2** [comment]
This is the expected behavior as described in the [docs](https://dm4t2.github.io/vue-currency-input/guide/#directive).
You have created a custom component if you want you to use `v-model` with a number on `v-text-field`:
https://codesandbox.io/s/using-vue-currency-input-with-vuetify-kd7d1?file=/src/components/VCurrencyField.vue
