### ISSUE TITLE
Minor version change: 1.19 to 1.22 has breaking changes and is not backwards compatible

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [dm4t2/vue-currency-input#164]
I appreciate the work you have put into this.

Please reconsider your numbering system for releases that contain breaking changes!  Semantic versioning is pretty widely accepted and understood now and a minor version change should be completely backwards compatible.  

I'm getting numerous errors on a what I would normally expect to be a simple update with minor bug fixes or new features that are still compatible considering the version change and realized only after the fact that this is a complete break from the previous behaviour in several ways.

I'm seeing several issues now including  continual errors about ".$ci is undefined" despite renaming the affected parseCurrency to "getValue" so I'll be digging into all the changes and try to sort it out as it appears there are *multiple* breaking changes.

**Comment by dm4t2** [comment]
Hi, you're right! As already mentioned in https://github.com/dm4t2/vue-currency-input/issues/149#issuecomment-675466480 I used to document the breaking changes only in the release notes rather than publishing a major version:

https://github.com/dm4t2/vue-currency-input/releases/tag/1.21.0
https://github.com/dm4t2/vue-currency-input/releases/tag/1.22.0

I will consider semantic versioning for future releases.
