### ISSUE TITLE
Vue component onLoad error

### ISSUE THREAD

**Issue by aldozumaran** [dm4t2/vue-currency-input#168]
I have a problem with directive  after component mounted.
with this configuration:
value: 0.54
onFocus: 54

 autoDecimalMode: false with different locale doesn't work
```
<q-input v-model="form.interest_rate"
                         ref="interest_rate"
                         v-currency="{
    locale: 'de-DE',
    currency: { prefix: null, suffix: ' %'},
    valueAsInteger: false,
    distractionFree: true,
    precision: 2,
    autoDecimalMode: false,
    valueRange: { min: 0, max: 100 },
    allowNegative: false
  }"
```

**Comment by bcronje** [comment]
Seems to work on [https://codesandbox.io/s/using-vue-currency-input-with-vuetify-forked-yplzm?file=/src/components/VCurrencyField.vue](https://codesandbox.io/s/using-vue-currency-input-with-vuetify-forked-yplzm?file=/src/components/VCurrencyField.vue) or are you expecting something else?

**Comment by dm4t2** [comment]
@aldozumaran You can not use a number with `v-model` when using the `v-currency` directive since it works directly on the formatted string. You need an additional state to handle both the displayed (formatted) value and its internal representation (number). This should be encapsulated in a custom component, see this example:

https://codesandbox.io/s/using-vue-currency-input-with-quasar-cjqgk?file=/src/components/QCurrencyInput.vue

For your use case, the component name should be `QPercentageInput` (very creative btw... 😉)

**Comment by aldozumaran** [comment]
I have this error

![image](https://user-images.githubusercontent.com/3183704/94408463-221c1800-0175-11eb-8c10-ba2109835460.png)
