### ISSUE TITLE
the plugin is broken in IE

### ISSUE THREAD

**Issue by LordPachelbel** [dm4t2/vue-currency-input#182]
Currency input fields aren't rendering at all in IE in the financial calculator I'm working on which uses this plugin. Instead Vue renders `<!---->` where the fields should be, and several errors are listed in the browser console.

The currency field on the plugin's [Playground page](https://dm4t2.github.io/vue-currency-input/playground/) is also broken in IE, and furthermore every page on [that entire website](https://dm4t2.github.io/vue-currency-input/) causes an alert box to appear asking if I want to debug the page.

Here's the console output from the website I'm working on. The first screenshot shows all of them collapsed:

![Screenshot 2020-12-10 184913](https://user-images.githubusercontent.com/10157193/101847602-34251a00-3b19-11eb-9133-7a0405a74d2c.png)

And here they are expanded:

![Screenshot 2020-12-10 184944](https://user-images.githubusercontent.com/10157193/101847612-37b8a100-3b19-11eb-89b0-e1826da2c97e.png)

![Screenshot 2020-12-10 185031](https://user-images.githubusercontent.com/10157193/101847620-3ab39180-3b19-11eb-8c8c-a27ce2a0c692.png)

If you need to see the financial calculator, [email me](mailto:jordan@brownboots.com) and I'll send you the URL, because the website hasn't officially been launched yet.

**Comment by dm4t2** [comment]
Hi, thanks for reporting. The docs and the playground should now work with IE 11.

Vue Currency Input requires polyfills for [Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) and [Array.prototype.includes()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) for usage with IE 11.
Since you are using the CDN download, you can include the following script **before** including the Vue Currency Input script
```
<script src="https://polyfill.io/v3/polyfill.min.js?features=Array.prototype.includes%2CObject.assign"></script>
```

See this example: https://codesandbox.io/s/vue-currency-input-direct-browser-usage-yjtci

**Comment by LordPachelbel** [comment]
Thank you for the quick response, and I didn't realize that polyfills that were necessary. Everything's working now. Thanks again.
