### ISSUE TITLE
input 98765432109876.01 see 98765432109876.02

### ISSUE THREAD

**Issue by chiangcho** [dm4t2/vue-currency-input#188]
when i set precision to 2 ,input 98765432109876.01 see 98765432109876.02。if the input less than 70************.01,the result is right

**Comment by dm4t2** [comment]
This issue is related to #129. Some large numbers close to [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) have accuracy problems. See this example in the Chrome console:

![image](https://user-images.githubusercontent.com/11592259/104071823-3ce93880-520a-11eb-8953-76e80fdc9866.png)

Ideally, it should be prevented to enter these values.

**Comment by chiangcho** [comment]
it  can  be prevented by using value range ,but it would be better  to provide  default max value. because different precision have different max value.

**Comment by dm4t2** [comment]
Fixed in [2.0.0-beta.3](https://github.com/dm4t2/vue-currency-input/releases/tag/2.0.0-beta.3)  🎉
