### ISSUE TITLE
Feature Request: emit event if out of range

### ISSUE THREAD

**Issue by chiangcho** [dm4t2/vue-currency-input#189]
Thanks for the great component. Would it be possible to add new opption, if out of range ,emit the event insted of automatically sets the respective threshold.

add another opption for validation can be triggred on input .

**Comment by dm4t2** [comment]
> Would it be possible to add new opption, if out of range ,emit the event insted of automatically sets the respective threshold.

No, but you can add your custom value range validation if the built-in does not meet your requirements. You can use [VeeValidate](https://logaretm.github.io/vee-validate/) for example: https://codesandbox.io/s/vue-currency-input-value-range-validation-with-vee-validate-xkk0v

> add another opption for validation can be triggred on input .

This option (`validateOnInput`) formerly existed and was removed in [Release 1.9.0](https://github.com/dm4t2/vue-currency-input/releases/tag/1.9.0). The problem was that you could not leave the value range (e.g. temporarily for corrections) and then you might be "trapped" in it.
