### ISSUE TITLE
'-' symbol disappears when changing locale dynamically

### ISSUE THREAD

**Issue by jean-1314** [dm4t2/vue-currency-input#194]
Hi! Thank you for this great directive.

I noticed weird behavior though when the value is negative: whenever a locale is changed dynamically, the minus symbol disappears.
Here is a [CodeSandbox demo](https://codesandbox.io/s/angry-monad-pcm09) with the reproduced issue, featuring an HTML input and a Vuetify input component.

**Comment by dm4t2** [comment]
Hi,

you can not use a number with `v-model` when using the `v-currency` directive since it works directly on the formatted string. You need an additional state to handle both the displayed (formatted) value and its internal representation (number). This should be encapsulated in a custom component, see this Vuetify example:

https://codesandbox.io/s/using-vue-currency-input-with-vuetify-kd7d1?file=/src/components/VCurrencyField.vue

**Comment by jean-1314** [comment]
Thank you for your reply!

I [forked your example](https://codesandbox.io/s/using-vue-currency-input-with-vuetify-forked-nq0zo?file=/src/App.vue), negated the value and added a button that switches locales. The problem persists: if you change locale, the minus sign is gone for good.
What am I doing wrong?  :)

**Comment by dm4t2** [comment]
I noticed that there's no fallback to the default options (including `allowNegative` set to `true`) when updating the `v-currency` options. This issue is already fixed in the upcoming v2 release. As a workaround, please include all options in your computed prop.

**Comment by jean-1314** [comment]
Added fallback options, and now everything is working like charm. Looking forward to v2!
