### ISSUE TITLE
Feature Request: Min & Max Range

### ISSUE THREAD

**Issue by tomirons** [dm4t2/vue-currency-input#2]
Would it be possible to add the ability to set a maximum and minimum accepted value? So that if a number is entered that puts the value over the maximum value or under the minimum value then the number is ignored and the current value is kept in the input.

For example, if the maximum value is `10` and the users enters `11`, the second `1` is ignored so that the input only shows the first `1` entered. The ignoring behavior is similar to how letters are ignored on input.

**Comment by dm4t2** [comment]
Yes, I think so. It would be a nice feature. I will have a look on it.

**Comment by dm4t2** [comment]
I spent some time playing around with the number range validation and finally decided to apply the validation when the input blurs. Otherwise it would be difficult edit existing values without clearing the whole input. There will also be situations in which the user is completely trapped when using both `min` and `max` (for example when `min=1` and `max=10` the input will be initialized with `1` and the user will not be able to change the value).

**Comment by dm4t2** [comment]
You can test the new number range validation on the demo page:
https://dm4t2.github.io/vue-currency-input/demo/
