### ISSUE TITLE
Emit unmasked value

### ISSUE THREAD

**Issue by chaosKP** [dm4t2/vue-currency-input#230]
In [222](https://github.com/dm4t2/vue-currency-input/issues/222) you described how to get the unmasked value by binding a modelValue from a "parent" component.
We create the Currency input dynamically and need it to emit the unmasked value without adding an extra component layer. 
Is there a way to do that? We are currently removing spaces, currency icon and everything by hand to get the right float and emit that, but that is not how it should be.

**Comment by dm4t2** [comment]
Can you provide a CodeSandbox to demostrate your use case? Thanks!

**Comment by chaosKP** [comment]
This is the way we would like to use it:
[https://codesandbox.io/s/using-vue-currency-input-with-quasar-veevalidate-forked-gj6ks?file=/src/QCurrencyInput.vue](https://codesandbox.io/s/using-vue-currency-input-with-quasar-veevalidate-forked-gj6ks?file=/src/QCurrencyInput.vue)

**Comment by dm4t2** [comment]
> We create the Currency input dynamically and need it to emit the unmasked value without adding an extra component layer.
> Is there a way to do that?

No, that's not possible. The `modelValue` binding is required. In your example, you also use an extra component layer. Why do you not use `v-model` instead of emitting a custom `value-changed` event? This works also with dynamic components:

https://codesandbox.io/s/using-vue-currency-input-with-quasar-veevalidate-forked-7kq6f?file=/src/QCurrencyInput.vue
