### ISSUE TITLE
New option `valueScaling`

### ISSUE THREAD

**Issue by dm4t2** [dm4t2/vue-currency-input#305]
see https://github.com/dm4t2/vue-currency-input/discussions/276

**Comment by envitraux** [comment]
I did create my own scaler wrapped around your component, but  the problem is that the less significant digits get truncated. Here is a snippet of the code. My component also stores the values in both USD and other currencies at the same time, so that is some of the extra code.

`const modelUsd = computed({
                get: () => props.modelValue && props.modelValue != 0.0 ? (props.modelValue / multiplier.value) : null,
                set: (usdVal) => {
                    if (!convertingCurrency) {
                        convertingCurrency = true
                        var scaledModel = props.modelValue && props.modelValue != 0.0 ? (props.modelValue / multiplier.value) : null
                        console.log('updateModelUsd', props.modelValue, scaledModel, usdVal, props.modelNative, toUSDRate.value)
                        if ((usdVal ?? 0.0).toFixed(2) != (scaledModel ?? 0.0).toFixed(2)) {
                            var nativeVal = (usdVal / toUSDRate.value)
                            emit('update:modelValue', usdVal && usdVal != 0.0 ? usdVal * multiplier.value : null)
                            emit('update:nativeValue', nativeVal && nativeVal != 0.0 ? nativeVal * multiplier.value : null)
                            precisionUsd.value = getPrecisionNeeded(usdVal)
                            precisionNative.value = getPrecisionNeeded(nativeVal)
                        }
                        convertingCurrency = false
                    }
                }
            })`
Here I use scaler as a factor of ten rather than named scales as you had suggested

`  const multiplier = computed(() => Math.pow(10, props.scale))`

**Comment by dm4t2** [comment]
Now available in [v2.3.0](https://github.com/dm4t2/vue-currency-input/releases/tag/2.3.0) 🎉
