### ISSUE TITLE
Inconsistent behaviour with Firefox + Vuetify 2

### ISSUE THREAD

**Issue by Sigmus** [dm4t2/vue-currency-input#397]
### Vue Currency Input version

3.0.5

### Vue version

2.7.14

### What browser are you using?

Firefox 115.0.2 (64-bit)

### What operating system are you using?

MacOS 13.4.1

### Reproduction link

https://codesandbox.io/p/sandbox/firefox-vue-currency-input-issue-smk3s6

### Describe your issue

When combining the lib with **Vuetify 2** and using **Firefox**, two problems happen:
- letters and other non-digits are accepted (they get removed `onBlur`)
- `hideGroupingSeparatorOnFocus: false` doesn't work

More context:
- v1 (directive) also accepts letters, but `distractionFree: false` works
- tried to figure out what changed here (https://github.com/dm4t2/vue-currency-input/issues/175) with no success
- with Vuetify 3 / Vue 3, everything works fine: https://codesandbox.io/p/sandbox/still-cherry-f2q6y3

So it's the combination with Vuetify 2 that is causing the issue. I know this is a long shot, since the lib is working fine with other component libraries, but I was hoping anyone could have some clue on how to solve this. (no, I can't migrate to Vuetify 3 just yet).

Thanks for the great work @dm4t2 !

**Comment by dm4t2** [comment]
You can stick to v3.0.0 as a workaround: https://codesandbox.io/p/sandbox/firefox-vue-currency-input-issue-forked-49wqzy  

The original fix for #175 uses events for exchanging data:  https://github.com/dm4t2/vue-currency-input/commit/4b2f75172f60f031cd075365016214071a8f0b3b

Since [v3.0.1](https://github.com/dm4t2/vue-currency-input/releases/tag/3.0.1) the implementation uses callback functions instead of events because of issues in Vue 3 with component libs (Element Plus/Quasar): https://github.com/dm4t2/vue-currency-input/commit/59b8b405211c0fa0f337b118ab8d46001f030da6

**Comment by Sigmus** [comment]
Great, thanks!
