### ISSUE TITLE
Adding options watcher in Quasar example causes input to malfunction

### ISSUE THREAD

**Issue by vincemammoliti** [dm4t2/vue-currency-input#400]
### Vue Currency Input version

3.0.5

### Vue version

3.3.4

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction link

https://codesandbox.io/s/vue-currency-input-integration-with-quasar-forked-2h9ksy?file=/src/QCurrencyInput.vue

### Describe your issue

I have noticed this issue in an app I'm developing which utilises Quasar. I then tried to replicate it with the Quasar example linked from the docs. The reproduction link provided is forked from that example, and only has added a watcher on the options prop as described in the docs (https://dm4t2.github.io/vue-currency-input/guide.html#external-props-changes).

The issue is that the input malfunctions when a watcher is added to make the options reactive for changes.

**Comment by dm4t2** [comment]
For some reason, the options prop watcher is triggered on each input with Quasar. I don't why because the options object does actually not change.

As a workaround, you can pass each option (for example `currency`) as a single prop: https://codesandbox.io/s/vue-currency-input-integration-with-quasar-forked-s7l7sm?file=/src/QCurrencyInput.vue

**Comment by daniandl** [comment]
This also happens with Vuetify's text field FYI
