### ISSUE TITLE
How can I get raw value in directive?

### ISSUE THREAD

**Issue by briangdr22** [dm4t2/vue-currency-input#9]
Hi, I tried to get raw value in directive but I don't know how to get it.

Is possible this in the directive?

**Comment by npenner** [comment]
Hello,
thanks for the module. Basically working great but i am facing the same issue while using it as a directive. It is not outputting the raw number. Is this expected?

code looks like this. 

```
<input
v-if="isMoneyField"
class="currencyInput"
v-model="model.upperValue"
:required="isBetweenOperator"
:min="minUpperValue(model.lowerValue, inputType)"
@input="emitChanges"
@keydown.enter.prevent
v-currency="{locale, currency, distractionFree}"
>

data() {
    return {
      currency: "EUR",
      locale: "de-DE",
      distractionFree: true
    };
  }
```

Behaviour is this:

![currencyinput](https://user-images.githubusercontent.com/13521240/56720441-2142b380-6743-11e9-9322-3e590217081c.gif)

Any help or hints much appreciated.
Thanks

**Comment by dm4t2** [comment]
@briangdr22: 
Yes, check out this example: https://codesandbox.io/s/6y6joo3orz
Each time the value changes, a `change` event is fired, passing the raw number value as `numberValue` in the event's `detail` property. Please note, that the event name will probably change in the next release (1.4.0)

@npenner:
This is intended, since the directive is working on the input's string value. You have to use the `<currency-input>` component, if you want to bind a number value with `v-model`.

**Comment by dm4t2** [comment]
I have introduced the instance method `$parseCurrency` in release 1.4.0 to easily get the raw number value from the formatted string.

See in the docs: https://dm4t2.github.io/vue-currency-input/guide/#directive
